modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/MUYUTwilighter/Croparia/issues"
license = "MIT"

[[mods]]
modId = "croparia"
version = "${version}"
displayName = "Croparia-If"
authors = "MUYU_Twilighter, xwjcool"
description = '''
A completely rewritten project from Dalarion's Croparia 4.5.
You should only install either Croparia or Croparia-If at the same time.
'''
logoFile = "assets/croparia/icon.png"

[[dependencies.croparia]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.croparia]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.croparia]]
modId = "rei"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
