import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "com.modrinth.minotaur" version "2.+"
    id 'net.darkhax.curseforgegradle' version '1.1.26'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive = false }

    // REI
    modRuntimeOnly("me.shedaniel:RoughlyEnoughItems-fabric:$rei_version")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:$rei_version")
    // RER
    modRuntimeOnly("curse.maven:roughly-enough-resources-325625:4721545")

    // EMI
    modCompileOnly("dev.emi:emi-fabric:${emi_version}:api")
    modLocalRuntime("dev.emi:emi-fabric:${emi_version}")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}

base {
    archivesName = archives_base_name + "-fabric"
}

modrinth {
    token = System.getenv("MODRINTH_MOD_PUBLISH")
    projectId = "croparia-if"
    versionName = archives_base_name + "-fabric-" + mod_version
    versionNumber = mod_version
    versionType = mod_version.contains("pre") ? "beta" : "release"
    uploadFile = remapJar
    gameVersions = [minecraft_version]
    loaders = ["fabric"]
    changelog = rootProject.file("changelog.md").text
    dependencies {
        required.project "architectury-api"
        incompatible.project "croparia"
    }
}

tasks.register('curseforge', TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_MOD_PUBLISH")
    def mainFile = upload('971004', remapJar)
    mainFile.displayName = archives_base_name + "-fabric-" + mod_version
    mainFile.releaseType = mod_version.contains("pre") ? "beta" : "release"
    mainFile.changelog = rootProject.file("changelog.md").text
    mainFile.changelogType = 'markdown'
    mainFile.gameVersions = [minecraft_version]
    mainFile.addJavaVersion("Java 17")
    mainFile.addEnvironment("server", "client")
    mainFile.addModLoader("fabric")
    mainFile.addRequirement("architectury-api")
    mainFile.addIncompatibility("croparia")
}