plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "com.modrinth.minotaur" version "2.+"
    id 'com.matthewprenger.cursegradle' version '1.4.0'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "croparia-if-common.mixins.json", "croparia-if-forge.mixins.json"
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${forge_version}"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury-forge:${architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))

    // REI
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-forge:$rei_version"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-forge:$rei_version"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-forge:$rei_version"
    // RER
    modRuntimeOnly "curse.maven:roughly-enough-resources-325625:4721546"

    // EMI
    modCompileOnly "dev.emi:emi-forge:${emi_version}:api"
    modCompileOnly "dev.emi:emi-forge:${emi_version}"
    modRuntimeOnly "dev.emi:emi-forge:${emi_version}"
//    // KubeJS
//    modImplementation "dev.latvian.mods:kubejs-forge:${kubejs_version}"
//    modImplementation "dev.latvian.mods:rhino-forge:${rhino_version}"

    // Mekanism
    modRuntimeOnly "curse.maven:mekanism-268560:6123077"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}

base {
    archivesName = archives_base_name + "-forge"
}

modrinth {
    token = System.getenv("MODRINTH_MOD_PUBLISH")
    projectId = "croparia-if"
    versionName = archives_base_name + "-forge-" + mod_version
    versionNumber = mod_version
    uploadFile = remapJar
    gameVersions = ["1.20.1"]
    loaders = ["forge"]
    changelog = rootProject.file("changelog.md").text
    dependencies {
        required.project "architectury-api"
        incompatible.project "croparia"
    }
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_MOD_PUBLISH")
    project {
        apiKey = System.getenv("CURSEFORGE_MOD_PUBLISH")
        id = '971004'
        releaseType = 'release'
        addGameVersion minecraft_version
        changelog = rootProject.file("changelog.md")
        changelogType = 'markdown'
        relations {
            requiredDependency "architectury-api"
            incompatible "croparia"
        }
        mainArtifact(remapJar) {
            displayName = archives_base_name + "-forge-" + mod_version
        }
    }
}